name: Test

on:
  push:
    branches:
      - master
env:
  ETHERSCAN_TOKEN: ${{ secrets.ETHERSCAN_TOKEN }}
  BSSCAN_TOKEN: ${{ secrets.BSSCAN_TOKEN }}

jobs:

  standardtest:

    runs-on: ubuntu-latest

    steps:
      - name: Check out github repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Set up python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Set pip cache directory path
        id: pip-cache-dir-path
        run: |
          echo "::set-output name=dir::$(pip cache dir)"

      - name: Restore pip cache
        uses: actions/cache@v2
        id: pip-cache
        with:
          path: |
            ${{ steps.pip-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
            ${{ runner.os }}-pip-

      - name: Install python dependencies
        run: pip install -r requirements.txt

      - name: run tests
        run: pytest test.py
